// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Chore struct {
	ID   int64
	Name string
}

type Duty struct {
	ID           int64
	EmployeeID   int64
	ChoreID      int64
	AssignedDate time.Time
	Status       string
}

type Employee struct {
	ID   int64
	Name string
}
